#!/usr/bin/env python
import sys
import rospy
from std_msgs.msg import String
from qt_nuitrack_app.msg import Faces
from qt_robot_interface.srv import *

em_index = 0
def sad_smile(em_index):
    if em_index == 0:
        emotionShow("QT/sad")
        rospy.sleep(2)
    elif em_index == 1:
        emotionShow("QT/calming_down")
        rospy.sleep(2)
    
    
if __name__ == '__main__':
    rospy.init_node('my_tutorial_node')
    rospy.loginfo("my_tutorial_node started!")

    emotionShow = rospy.ServiceProxy('/qt_robot/emotion/show', emotion_show)
    speech_pub = rospy.Publisher('/qt_robot/speech/say', String, queue_size=1)

    # define ros subscriber
    #rospy.Subscriber('/qt_nuitrack_app/faces', Faces, sad_smile)
    sad_smile(em_index)
    try:
        rospy.spin()
    except KeyboardInterrupt:
        pass

    rospy.loginfo("finsihed!")
